language: go


branches:
  only:
    - develop
    - master
#notifications:
#  email:
#    recipients:
#      - wtt.2012@gmail.com
#  on_success: change
#  on_failure: always

install:
  - go get -u


script:
  - echo $COVERALLS_TOKEN
#  - go test -v -covermode=count -coverprofile=coverage.out
#  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -i -v -race ./...
  - go test -race -covermode atomic -coverprofile=coverage.cov
  - goveralls -coverprofile=coverage.cov -service=travis-ci

#  - (go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

go:
  - 1.9.x
  - 1.10.x

env:
  global:
    secure: UoAxs7DjoiPFPhTS4wOeDgK73MXRQivqtkEQYfpm6hfK56u/YdngvAX4/CMEE0ExKD6yMFiiFQWjE8SlC7v7AwIe7Xp2b5HYtcgPOTsO3bl07iSWt1G7FOuR+fh7mwX692krLARiHhZ2mUv8OXYsoUglz3EQ3BoS9ny/FZV5HBEOuHhFQNt1lUllwFl7LZrCHUpR9TuPzXaiWIddgHYquFamrUjeW2DbwxtvExwKeuturdyrZ62YHaEkQZmxEL54Q8sOO7BgylbdY7yIbeGDe8YeEkqhOXZeFI9umaIFzFwJXfAeGv0sGGPYx/XpJkeWTBRUzK69VrrLEFH4hVo+t366lYab3D5hXZo5NJjEwXQX80ABkCdmnFde7bm5D4gMINRpOFkZJkjhPeFm5ICpUNq5YmAs7pS3VJkt6G3mQdbNKZ5To98MyCPCYC+s8Vp5NugLx9t9TLZ9sopZA/2VNMpZpivF2nQklWJiiPhdEjTbiy7eba7fE84OAxQXW/5akExTvm8XBnkRMMjI3osqwlRImSrNLCaqK42CDeDafZMd247YlIxlksVlWeEmm92T7edprBZjpakWacdZz+J9wv5/F0EG+/hPRGidBRLTshVa18fYsCniB5pszesqrUtsNqMassloxc5jE3XXzlxzg3mwzg93JrNm4NYGlNHiMQU=


