language: go


branches:
  only:
    - master
#notifications:
#  email:
#    recipients:
#      - wtt.2012@gmail.com
#  on_success: change
#  on_failure: always

install:
#  - go get -u


script:
  - echo $COVERALLS_TOKEN
#  - go test -v -covermode=count -coverprofile=coverage.out
#  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
#  - go test -i -v -race ./...
#  - go test -race -covermode atomic -coverprofile=coverage.cov
#  - goveralls -coverprofile=coverage.cov -service=travis-ci

#  - (go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

go:
  - 1.9.x
  - 1.10.x

